services:
  web:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - 5173:5173
      - 3000:3000
    command: sh -c "npx json-server src/api/data.json & npm run dev"
